name: .NET Core Build and Publish

env:
  DOTNET_VERSION: "3.1.401"
  OUTPUT_PATH: ${{ github.workspace }}/artifact/

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build_and_publish:
    env:
      ASSEMBLY_VERSION: 1.0.0.${{ github.run_number }}
      ADR_PROJECT_FILE: "./src/adr/adr-cli.csproj"
      CONFIGURATION: "Release"
      DOTNET_CLI_TELEMETRY_OPTOUT: 1

    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, windows-latest, macOS-latest]
        include:
          - os: ubuntu-latest
            runtime: linux-x64
          - os: macOS-latest
            runtime: osx-x64
          - os: windows-latest
            runtime: win-x64

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Build
      run: dotnet build --runtime ${{ matrix.runtime }} --configuration ${{ env.CONFIGURATION }} --nologo -p:Version=${{ env.ASSEMBLY_VERSION }}
      working-directory: ./src

    - name: Test
      run: dotnet test --runtime ${{ matrix.runtime }} --no-restore --verbosity normal
      working-directory: ./src

    - name: Publish for ${{ matrix.runtime }} single executable
      run: dotnet publish ${{ env.ADR_PROJECT_FILE }} --runtime ${{ matrix.runtime }} -c ${{ env.CONFIGURATION }} --no-restore --no-build /p:PublishSingleFile=true --output ${{ env.OUTPUT_PATH }}/${{ matrix.runtime }}-portable/ --self-contained true /p:PublishTrimmed=true

    - name: Publish for ${{ matrix.runtime }} single executable
      run: dotnet publish ${{ env.ADR_PROJECT_FILE }} --runtime ${{ matrix.runtime }} -c ${{ env.CONFIGURATION }} --no-restore --no-build /p:PublishSingleFile=true --output ${{ env.OUTPUT_PATH }}/${{ matrix.runtime }}-dependent/ --self-contained false

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ADR-CLI-tool
        path: ${{ env.OUTPUT_PATH }}
