name: .NET Core Build and Publish

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  env:
    version: 1.0.0.{{GITHUB_RUN_NUMBER}}
    cliProjectFile: ./src/adr/adr-cli.csproj
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./src

    - name: Build
      run: dotnet build --runtime win7-x64 --configuration Release --no-restore -p:Version=$version
      working-directory: ./src

    - name: Test
      run: dotnet test --runtime win7-x64 --no-restore --verbosity normal
      working-directory: ./src

    - name: Publish for Windows-x64
      run: dotnet publish $cliProjectFile --runtime win7-x64 -c Release --no-restore --no-build --output ${{ github.workspace }}/artifact/windows/

    - name: Publish for Windows-x64 single executable
      run: dotnet publish $cliProjectFile --runtime win7-x64 -c Release --no-restore --no-build /p:PublishSingleFile=true --output ${{ github.workspace }}/artifact/windows-portable/

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ADR-CLI-tool-Windows-x64
        path: ${{ github.workspace }}/artifact/
